services:
  site-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: site-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge